/*  ------------------------------------------------------------------
    Copyright (c) 2011-2020 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

// Generated by gencpp from file rai_msgs/SendJointTrajectory.msg
// DO NOT EDIT!

#ifndef RAI_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H
#define RAI_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H

#include <ros/service_traits.h>

#include "../rai_msgs/SendJointTrajectoryRequest.h"
#include "../rai_msgs/SendJointTrajectoryResponse.h"

namespace rai_msgs {

struct SendJointTrajectory {

  typedef SendJointTrajectoryRequest Request;
  typedef SendJointTrajectoryResponse Response;
  Request request;
  Response response;

  typedef Request RequestType;
  typedef Response ResponseType;

}; // struct SendJointTrajectory
} // namespace rai_msgs

namespace ros {
namespace service_traits {

template<>
struct MD5Sum< ::rai_msgs::SendJointTrajectory > {
  static const char* value() {
    return "b8ca7270ae29f6a2b069682a8cfd473e";
  }

  static const char* value(const ::rai_msgs::SendJointTrajectory&) { return value(); }
};

template<>
struct DataType< ::rai_msgs::SendJointTrajectory > {
  static const char* value() {
    return "rai_msgs/SendJointTrajectory";
  }

  static const char* value(const ::rai_msgs::SendJointTrajectory&) { return value(); }
};

// service_traits::MD5Sum< ::rai_msgs::SendJointTrajectoryRequest> should match
// service_traits::MD5Sum< ::rai_msgs::SendJointTrajectory >
template<>
struct MD5Sum< ::rai_msgs::SendJointTrajectoryRequest> {
  static const char* value() {
    return MD5Sum< ::rai_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::rai_msgs::SendJointTrajectoryRequest&) {
    return value();
  }
};

// service_traits::DataType< ::rai_msgs::SendJointTrajectoryRequest> should match
// service_traits::DataType< ::rai_msgs::SendJointTrajectory >
template<>
struct DataType< ::rai_msgs::SendJointTrajectoryRequest> {
  static const char* value() {
    return DataType< ::rai_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::rai_msgs::SendJointTrajectoryRequest&) {
    return value();
  }
};

// service_traits::MD5Sum< ::rai_msgs::SendJointTrajectoryResponse> should match
// service_traits::MD5Sum< ::rai_msgs::SendJointTrajectory >
template<>
struct MD5Sum< ::rai_msgs::SendJointTrajectoryResponse> {
  static const char* value() {
    return MD5Sum< ::rai_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::rai_msgs::SendJointTrajectoryResponse&) {
    return value();
  }
};

// service_traits::DataType< ::rai_msgs::SendJointTrajectoryResponse> should match
// service_traits::DataType< ::rai_msgs::SendJointTrajectory >
template<>
struct DataType< ::rai_msgs::SendJointTrajectoryResponse> {
  static const char* value() {
    return DataType< ::rai_msgs::SendJointTrajectory >::value();
  }
  static const char* value(const ::rai_msgs::SendJointTrajectoryResponse&) {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAI_MSGS_MESSAGE_SENDJOINTTRAJECTORY_H
