/*  ------------------------------------------------------------------
    Copyright (c) 2011-2020 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

// Generated by gencpp from file rai_msgs/StringString.msg
// DO NOT EDIT!

#ifndef RAI_MSGS_MESSAGE_STRINGSTRING_H
#define RAI_MSGS_MESSAGE_STRINGSTRING_H

#include <ros/service_traits.h>

#include "../rai_msgs/StringStringRequest.h"
#include "../rai_msgs/StringStringResponse.h"

namespace rai_msgs {

struct StringString {

  typedef StringStringRequest Request;
  typedef StringStringResponse Response;
  Request request;
  Response response;

  typedef Request RequestType;
  typedef Response ResponseType;

}; // struct StringString
} // namespace rai_msgs

namespace ros {
namespace service_traits {

template<>
struct MD5Sum< ::rai_msgs::StringString > {
  static const char* value() {
    return "671f8e4998eaec79f1c47e339dfd527b";
  }

  static const char* value(const ::rai_msgs::StringString&) { return value(); }
};

template<>
struct DataType< ::rai_msgs::StringString > {
  static const char* value() {
    return "rai_msgs/StringString";
  }

  static const char* value(const ::rai_msgs::StringString&) { return value(); }
};

// service_traits::MD5Sum< ::rai_msgs::StringStringRequest> should match
// service_traits::MD5Sum< ::rai_msgs::StringString >
template<>
struct MD5Sum< ::rai_msgs::StringStringRequest> {
  static const char* value() {
    return MD5Sum< ::rai_msgs::StringString >::value();
  }
  static const char* value(const ::rai_msgs::StringStringRequest&) {
    return value();
  }
};

// service_traits::DataType< ::rai_msgs::StringStringRequest> should match
// service_traits::DataType< ::rai_msgs::StringString >
template<>
struct DataType< ::rai_msgs::StringStringRequest> {
  static const char* value() {
    return DataType< ::rai_msgs::StringString >::value();
  }
  static const char* value(const ::rai_msgs::StringStringRequest&) {
    return value();
  }
};

// service_traits::MD5Sum< ::rai_msgs::StringStringResponse> should match
// service_traits::MD5Sum< ::rai_msgs::StringString >
template<>
struct MD5Sum< ::rai_msgs::StringStringResponse> {
  static const char* value() {
    return MD5Sum< ::rai_msgs::StringString >::value();
  }
  static const char* value(const ::rai_msgs::StringStringResponse&) {
    return value();
  }
};

// service_traits::DataType< ::rai_msgs::StringStringResponse> should match
// service_traits::DataType< ::rai_msgs::StringString >
template<>
struct DataType< ::rai_msgs::StringStringResponse> {
  static const char* value() {
    return DataType< ::rai_msgs::StringString >::value();
  }
  static const char* value(const ::rai_msgs::StringStringResponse&) {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAI_MSGS_MESSAGE_STRINGSTRING_H
