/*  ------------------------------------------------------------------
    Copyright (c) 2011-2020 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

// Generated by gencpp from file rai_msgs/WSG_50_command.msg
// DO NOT EDIT!

#ifndef RAI_MSGS_MESSAGE_WSG_50_COMMAND_H
#define RAI_MSGS_MESSAGE_WSG_50_COMMAND_H

#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace rai_msgs {
template <class ContainerAllocator>
struct WSG_50_command_ {
  typedef WSG_50_command_<ContainerAllocator> Type;

  WSG_50_command_()
    : header()
    , position_mm(0.0)
    , force(0.0)  {
  }
  WSG_50_command_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position_mm(0.0)
    , force(0.0)  {
    (void)_alloc;
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

  typedef float _position_mm_type;
  _position_mm_type position_mm;

  typedef float _force_type;
  _force_type force;

  typedef boost::shared_ptr< ::rai_msgs::WSG_50_command_<ContainerAllocator>> Ptr;
  typedef boost::shared_ptr< ::rai_msgs::WSG_50_command_<ContainerAllocator> const> ConstPtr;

}; // struct WSG_50_command_

typedef ::rai_msgs::WSG_50_command_<std::allocator<void>> WSG_50_command;

typedef boost::shared_ptr< ::rai_msgs::WSG_50_command > WSG_50_commandPtr;
typedef boost::shared_ptr< ::rai_msgs::WSG_50_command const> WSG_50_commandConstPtr;

// constants requiring out of line definition

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rai_msgs::WSG_50_command_<ContainerAllocator>& v) {
  ros::message_operations::Printer< ::rai_msgs::WSG_50_command_<ContainerAllocator>>::stream(s, "", v);
  return s;
}

} // namespace rai_msgs

namespace ros {
namespace message_traits {

// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/msg'], 'rai_msgs': ['/home/mtoussai/git/mlr/share/rai/rai/rai_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']

template <class ContainerAllocator>
struct IsFixedSize< ::rai_msgs::WSG_50_command_<ContainerAllocator>>
      : FalseType
{ };

template <class ContainerAllocator>
struct IsFixedSize< ::rai_msgs::WSG_50_command_<ContainerAllocator> const>
  : FalseType
{ };

template <class ContainerAllocator>
struct IsMessage< ::rai_msgs::WSG_50_command_<ContainerAllocator>>
      : TrueType
{ };

template <class ContainerAllocator>
struct IsMessage< ::rai_msgs::WSG_50_command_<ContainerAllocator> const>
  : TrueType
{ };

template <class ContainerAllocator>
struct HasHeader< ::rai_msgs::WSG_50_command_<ContainerAllocator>>
      : TrueType
{ };

template <class ContainerAllocator>
struct HasHeader< ::rai_msgs::WSG_50_command_<ContainerAllocator> const>
  : TrueType
{ };

template<class ContainerAllocator>
struct MD5Sum< ::rai_msgs::WSG_50_command_<ContainerAllocator>> {
  static const char* value() {
    return "a514a03251c5097dc263cec0c1c78d42";
  }

  static const char* value(const ::rai_msgs::WSG_50_command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa514a03251c5097dULL;
  static const uint64_t static_value2 = 0xc263cec0c1c78d42ULL;
};

template<class ContainerAllocator>
struct DataType< ::rai_msgs::WSG_50_command_<ContainerAllocator>> {
  static const char* value() {
    return "rai_msgs/WSG_50_command";
  }

  static const char* value(const ::rai_msgs::WSG_50_command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rai_msgs::WSG_50_command_<ContainerAllocator>> {
  static const char* value() {
    return "Header header\n\
float32 position_mm # in millimeters\n\
float32 force\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::rai_msgs::WSG_50_command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros {
namespace serialization {

template<class ContainerAllocator> struct Serializer< ::rai_msgs::WSG_50_command_<ContainerAllocator>> {
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m) {
    stream.next(m.header);
    stream.next(m.position_mm);
    stream.next(m.force);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct WSG_50_command_

} // namespace serialization
} // namespace ros

namespace ros {
namespace message_operations {

template<class ContainerAllocator>
struct Printer< ::rai_msgs::WSG_50_command_<ContainerAllocator>> {
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rai_msgs::WSG_50_command_<ContainerAllocator>& v) {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator>>::stream(s, indent + "  ", v.header);
    s << indent << "position_mm: ";
    Printer<float>::stream(s, indent + "  ", v.position_mm);
    s << indent << "force: ";
    Printer<float>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAI_MSGS_MESSAGE_WSG_50_COMMAND_H
