BASE = ../../..

OBJS = main.o prob.o IpoptConstrainedProblem.o

DEPEND = Core Optim

IPOPT = 1

#CPATHS += ${HOME}/tmp/ipopt/Ipopt-3.12.2/include
#LPATHS += ${HOME}/tmp/ipopt/Ipopt-3.12.2/lib
#LPATHS += ${HOME}/tmp/ipopt/coinhsl-linux-x86_64-2014.01.10/lib

#CXX = mpic++
#CXXFLAGS += -fopenmp

#DEPEND = Core MCTS Gui

#LIBS += -lipopt -lcoinhsl

include $(BASE)/build/generic.mk
