/*  ------------------------------------------------------------------
    Copyright (c) 2011-2020 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

// Generated by gencpp from file RelationalMachine/Literal.msg
// DO NOT EDIT!

#ifndef RELATIONALMACHINE_MESSAGE_LITERAL_H
#define RELATIONALMACHINE_MESSAGE_LITERAL_H

#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

namespace RelationalMachine {
template <class ContainerAllocator>
struct Literal_ {
  typedef Literal_<ContainerAllocator> Type;

  Literal_()
    : literal()
    , parameters()  {
  }
  Literal_(const ContainerAllocator& _alloc)
    : literal(_alloc)
    , parameters(_alloc)  {
  }

  typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >, typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >>::other >  _literal_type;
  _literal_type literal;

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _parameters_type;
  _parameters_type parameters;

  typedef boost::shared_ptr< ::RelationalMachine::Literal_<ContainerAllocator>> Ptr;
  typedef boost::shared_ptr< ::RelationalMachine::Literal_<ContainerAllocator> const> ConstPtr;

}; // struct Literal_

typedef ::RelationalMachine::Literal_<std::allocator<void>> Literal;

typedef boost::shared_ptr< ::RelationalMachine::Literal > LiteralPtr;
typedef boost::shared_ptr< ::RelationalMachine::Literal const> LiteralConstPtr;

// constants requiring out of line definition

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::RelationalMachine::Literal_<ContainerAllocator>& v) {
  ros::message_operations::Printer< ::RelationalMachine::Literal_<ContainerAllocator>>::stream(s, "", v);
  return s;
}

} // namespace RelationalMachine

namespace ros {
namespace message_traits {

// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']

template <class ContainerAllocator>
struct IsFixedSize< ::RelationalMachine::Literal_<ContainerAllocator>>
      : FalseType
{ };

template <class ContainerAllocator>
struct IsFixedSize< ::RelationalMachine::Literal_<ContainerAllocator> const>
  : FalseType
{ };

template <class ContainerAllocator>
struct IsMessage< ::RelationalMachine::Literal_<ContainerAllocator>>
      : TrueType
{ };

template <class ContainerAllocator>
struct IsMessage< ::RelationalMachine::Literal_<ContainerAllocator> const>
  : TrueType
{ };

template <class ContainerAllocator>
struct HasHeader< ::RelationalMachine::Literal_<ContainerAllocator>>
      : FalseType
{ };

template <class ContainerAllocator>
struct HasHeader< ::RelationalMachine::Literal_<ContainerAllocator> const>
  : FalseType
{ };

template<class ContainerAllocator>
struct MD5Sum< ::RelationalMachine::Literal_<ContainerAllocator>> {
  static const char* value() {
    return "cd28a6104f0aa6812b154a6942018980";
  }

  static const char* value(const ::RelationalMachine::Literal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcd28a6104f0aa681ULL;
  static const uint64_t static_value2 = 0x2b154a6942018980ULL;
};

template<class ContainerAllocator>
struct DataType< ::RelationalMachine::Literal_<ContainerAllocator>> {
  static const char* value() {
    return "RelationalMachine/Literal";
  }

  static const char* value(const ::RelationalMachine::Literal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::RelationalMachine::Literal_<ContainerAllocator>> {
  static const char* value() {
    return "string[] literal\n\
string parameters\n\
";
  }

  static const char* value(const ::RelationalMachine::Literal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros {
namespace serialization {

template<class ContainerAllocator> struct Serializer< ::RelationalMachine::Literal_<ContainerAllocator>> {
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m) {
    stream.next(m.literal);
    stream.next(m.parameters);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Literal_

} // namespace serialization
} // namespace ros

namespace ros {
namespace message_operations {

template<class ContainerAllocator>
struct Printer< ::RelationalMachine::Literal_<ContainerAllocator>> {
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::RelationalMachine::Literal_<ContainerAllocator>& v) {
    s << indent << "literal[]" << std::endl;
    for(size_t i = 0; i < v.literal.size(); ++i) {
      s << indent << "  literal[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >>::stream(s, indent + "  ", v.literal[i]);
    }
    s << indent << "parameters: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >>::stream(s, indent + "  ", v.parameters);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RELATIONALMACHINE_MESSAGE_LITERAL_H
