/*  ------------------------------------------------------------------
    Copyright (c) 2011-2020 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

// Generated by gencpp from file rai_srv/StringString.msg
// DO NOT EDIT!

#ifndef RAI_SRV_MESSAGE_STRINGSTRING_H
#define RAI_SRV_MESSAGE_STRINGSTRING_H

#include <ros/service_traits.h>

#include <msgs/StringStringRequest.h>
#include <msgs/StringStringResponse.h>

namespace rai_srv {

struct StringString {

  typedef StringStringRequest Request;
  typedef StringStringResponse Response;
  Request request;
  Response response;

  typedef Request RequestType;
  typedef Response ResponseType;

}; // struct StringString
} // namespace rai_srv

namespace ros {
namespace service_traits {

template<>
struct MD5Sum< ::rai_srv::StringString > {
  static const char* value() {
    return "671f8e4998eaec79f1c47e339dfd527b";
  }

  static const char* value(const ::rai_srv::StringString&) { return value(); }
};

template<>
struct DataType< ::rai_srv::StringString > {
  static const char* value() {
    return "rai_srv/StringString";
  }

  static const char* value(const ::rai_srv::StringString&) { return value(); }
};

// service_traits::MD5Sum< ::rai_srv::StringStringRequest> should match
// service_traits::MD5Sum< ::rai_srv::StringString >
template<>
struct MD5Sum< ::rai_srv::StringStringRequest> {
  static const char* value() {
    return MD5Sum< ::rai_srv::StringString >::value();
  }
  static const char* value(const ::rai_srv::StringStringRequest&) {
    return value();
  }
};

// service_traits::DataType< ::rai_srv::StringStringRequest> should match
// service_traits::DataType< ::rai_srv::StringString >
template<>
struct DataType< ::rai_srv::StringStringRequest> {
  static const char* value() {
    return DataType< ::rai_srv::StringString >::value();
  }
  static const char* value(const ::rai_srv::StringStringRequest&) {
    return value();
  }
};

// service_traits::MD5Sum< ::rai_srv::StringStringResponse> should match
// service_traits::MD5Sum< ::rai_srv::StringString >
template<>
struct MD5Sum< ::rai_srv::StringStringResponse> {
  static const char* value() {
    return MD5Sum< ::rai_srv::StringString >::value();
  }
  static const char* value(const ::rai_srv::StringStringResponse&) {
    return value();
  }
};

// service_traits::DataType< ::rai_srv::StringStringResponse> should match
// service_traits::DataType< ::rai_srv::StringString >
template<>
struct DataType< ::rai_srv::StringStringResponse> {
  static const char* value() {
    return DataType< ::rai_srv::StringString >::value();
  }
  static const char* value(const ::rai_srv::StringStringResponse&) {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RAI_SRV_MESSAGE_STRINGSTRING_H
