// Generated by gencpp from file mlr_srv/StringString.msg
// DO NOT EDIT!


#ifndef MLR_SRV_MESSAGE_STRINGSTRING_H
#define MLR_SRV_MESSAGE_STRINGSTRING_H

#include <ros/service_traits.h>


#include <msgs/StringStringRequest.h>
#include <msgs/StringStringResponse.h>


namespace mlr_srv
{

struct StringString
{

typedef StringStringRequest Request;
typedef StringStringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StringString
} // namespace mlr_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mlr_srv::StringString > {
  static const char* value()
  {
    return "671f8e4998eaec79f1c47e339dfd527b";
  }

  static const char* value(const ::mlr_srv::StringString&) { return value(); }
};

template<>
struct DataType< ::mlr_srv::StringString > {
  static const char* value()
  {
    return "mlr_srv/StringString";
  }

  static const char* value(const ::mlr_srv::StringString&) { return value(); }
};


// service_traits::MD5Sum< ::mlr_srv::StringStringRequest> should match 
// service_traits::MD5Sum< ::mlr_srv::StringString > 
template<>
struct MD5Sum< ::mlr_srv::StringStringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mlr_srv::StringString >::value();
  }
  static const char* value(const ::mlr_srv::StringStringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mlr_srv::StringStringRequest> should match 
// service_traits::DataType< ::mlr_srv::StringString > 
template<>
struct DataType< ::mlr_srv::StringStringRequest>
{
  static const char* value()
  {
    return DataType< ::mlr_srv::StringString >::value();
  }
  static const char* value(const ::mlr_srv::StringStringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mlr_srv::StringStringResponse> should match 
// service_traits::MD5Sum< ::mlr_srv::StringString > 
template<>
struct MD5Sum< ::mlr_srv::StringStringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mlr_srv::StringString >::value();
  }
  static const char* value(const ::mlr_srv::StringStringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mlr_srv::StringStringResponse> should match 
// service_traits::DataType< ::mlr_srv::StringString > 
template<>
struct DataType< ::mlr_srv::StringStringResponse>
{
  static const char* value()
  {
    return DataType< ::mlr_srv::StringString >::value();
  }
  static const char* value(const ::mlr_srv::StringStringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MLR_SRV_MESSAGE_STRINGSTRING_H
