/*  ------------------------------------------------------------------
    Copyright (c) 2011-2024 Marc Toussaint
    email: toussaint@tu-berlin.de

    This code is distributed under the MIT License.
    Please see <root-path>/LICENSE for details.
    --------------------------------------------------------------  */

#pragma once

#include "util.h"
#include "array.h"

#include <mutex>
#include <shared_mutex>
#include <condition_variable>
#include <thread>

namespace rai {

enum ThreadState { tsIsClosed=-6, tsToOpen=-1, tsLOOPING=-2, tsBEATING=-3, tsIDLE=0, tsToStep=1, tsToClose=-4,  tsFAILURE=-5,  }; //positive states indicate steps-to-go

//===========================================================================

template<class F> struct Callback {
  std::function<F> callback;
  const void* id; //only needed to delete callbacks from callback lists!
  Callback(const void* _id) : id(_id) {}
  Callback(const void* _id, const std::function<F>& c) : callback(c), id(_id) {}
  std::function<F>& call() { CHECK(callback, "is not initialized!!"); return callback; }
};

template<class F>
struct CallbackL : Array<Callback<F>*> {
  void removeCallback(const void* id) {
    uint i;
    for(i=0; i<this->N; i++) if(this->elem(i)->id==id) break;
    delete this->elem(i);
    this->remove(i);
  }
};

//===========================================================================

/// This RW lock counts revisions and broadcasts accesses to listeners; who is accessing can be logged; it has a unique name
struct Var_base : NonCopyable {
  std::shared_mutex rwlock;    ///< rwLock (handled via read/writeAccess)
  std::condition_variable_any cond;
  bool isWriteLocked = false;
  uint revision=0;
  double write_time=0.;        ///< clock time of last write access
  double data_time=0.;         ///< time stamp of the original data source
  CallbackL<void(Var_base*)> callbacks;

  Var_base() {}
  virtual ~Var_base() {}

  void addCallback(const std::function<void(Var_base*)>& call, const void* callbackID);

  /// @name access control
  /// to be called by a thread before access, returns the revision
  int read_lock();
  int write_lock();
  int read_unlock();
  int write_unlock();

  int getRevision() { rwlock.lock_shared(); int r=revision; rwlock.unlock_shared(); return r; }
};


//===========================================================================

//fwd declarations
template<class T> struct ReadToken;
template<class T> struct WriteToken;

/** When using a thread you may declare which variables the
    thread needs access to (for reading or writing). This is done by
    declaring members as 'Var<TYPE> name;' instead of 'TYPE
    name;'. The macro VAR(TYPE, name); makes this simpler. Access
    is the base class of Access.

    This also provides read/write 'tokens' (generated by get()
    and set()) which allow convenient and typed read/write access to
    the variable's content */
template<class T>
struct Var : Var_base {
  T data;
  int last_read_revision = 0;     ///< last revision that has been accessed (read or write)

  Var() {}
  Var(const T& x) : data(x) {}
  ~Var() {}

  void setValue(const T& x) { write_lock(); data=x; write_unlock(); }
  T getCopy() { T x; read_lock(); x=data; read_unlock(); return x; }

  ReadToken<T> get() { return ReadToken<T>(*this, data,  &last_read_revision); } ///< read access to the variable's data
  WriteToken<T> set() { return WriteToken<T>(*this, data/*, &last_read_revision*/); } ///< write access to the variable's data

  int read_lock() {  return last_read_revision = Var_base::read_lock(); }

  void waitForNextRevision(uint multipleRevisions=0) {
    waitForRevisionGreaterThan(last_read_revision+multipleRevisions);
  }
  uint waitForRevisionGreaterThan(uint rev){
    rwlock.lock_shared();
    while(revision<=rev) cond.wait(rwlock);
    uint i=revision;
    rwlock.unlock_shared();
    return i;
  }
  void waitForEq(const T& x) {
    rwlock.lock_shared();
    while(data!=x) cond.wait(rwlock);
    rwlock.unlock_shared();
  }
  int waitForNotEq(int x) {
    rwlock.lock_shared();
    while(data==x) cond.wait(rwlock);
    int y=data;
    rwlock.unlock_shared();
    return y;
  }
  ReadToken<T> waitForEqAndGet(const T& x) {
    rwlock.lock_shared();
    while(data!=x) cond.wait(rwlock);
    return ReadToken<T>(*this, data, &last_read_revision, true);
  }
  void addCallback(const std::function<void(Var_base*)>& call, const void* callbackID=0) {
    addCallback(call, callbackID);
  }
  void write(ostream& os) {
    read_lock();
    os <<"VAR [" <<getRevision() <<"] " <<data <<endl;
    read_unlock();
  }
  void incrementStatus(int delta=1) { write_lock(); data+=delta; write_unlock(); }
};

template<class T> std::ostream& operator<<(std::ostream& os, Var<T>& x) { x.write(os); return os; }

//===========================================================================

template<class T>
struct ReadToken {
  Var_base& var;
  T& data;
  ReadToken(Var_base& _var, T& _data, int* getRevision=nullptr, bool isAlreadyLocked=false)
      : var(_var), data(_data) {
    if(!isAlreadyLocked) var.read_lock();
    if(getRevision) *getRevision=var.revision;
  }
  ~ReadToken() { var.read_unlock(); }
  const T* operator->() { return &data; }
  operator const T& () { return data; }
  const T& operator()() { return data; }
};

template<class T>
struct WriteToken {
  Var_base& var;
  T& data;
  WriteToken(Var_base& _var, T& _data, int* getRevision=nullptr)
      : var(_var), data(_data) {
    var.write_lock();
    if(getRevision) *getRevision=var.revision+1;
  }
  WriteToken(const double& dataTime, Var_base& _var, T* _data, int* getRevision=nullptr)
      : var(_var), data(_data) {
    var.write_lock();
    var.data_time=dataTime;
    if(getRevision) *getRevision=var.revision+1;
  }
  ~WriteToken() { var.write_unlock(); }
  void operator=(const T& y) { data=y; }
  T* operator->() { return &data; }
  operator T& () { return data; }
  T& operator()() { return data; }
};

//===========================================================================
//
// Timing helpers
//

/// to meassure cycle and busy times
struct CycleTimer {
  typedef std::chrono::time_point<std::chrono::high_resolution_clock, std::chrono::duration<double>> timepoint;
  uint steps;
  arr mean, max;
  timepoint now, lastTime, lastZero;
  CycleTimer();
  ~CycleTimer();
  void reset();
  void tic(uint i);
  void cycleStart(){ tic(0); }
  void cycleDone(){ tic(1); }
  String report();
};

//===========================================================================
/**
 * A Thread does some calculation and shares the result via a VariableData.
 *
 * Inherit from the class Thread to create your own process.
 * You need to implement open(), close(), and step().
 * step() should contain the actual calculation.
 *
 * the Signaler indicates the state of the thread: positive=do steps, otherwise it is a ThreadState
 */
struct Thread {
  Var<int> status;
  String name;
  std::unique_ptr<std::thread> thread;    ///< the underlying pthread; nullptr iff not opened
  int tid;                    ///< system thread id
  Mutex stepMutex;            ///< This is set whenever the 'main' is in step (or open, or close) --- use this in all service methods callable from outside
  uint step_count;            ///< how often the step was called
  Array<Var_base*> variables; ///< variables this thread listens to
  Metronome metronome;        ///< used for beat-looping
  CycleTimer timer;           ///< measure how the time spend per cycle, within step, idle

  /// @name c'tor/d'tor
  /** DON'T open drivers/devices/files or so here in the constructor,
   * but in open(). Sometimes a module might be created only to see
   * which accesses it needs. The default constructure should really
   * do nothing
   *
   * beatIntervalSec=0. indicates full speed looping, beatIntervalSec=-1. indicates no looping (steps triggered by listening)
   */
  Thread(const char* _name, double beatIntervalSec=-1.);
  virtual ~Thread();

  // -- standard methods to start and close the thread
  void threadLoop(bool waitForOpened=false);  ///< loop, either with fixed beat or at full speed
  void threadClose(double timeoutForce=-1.);  ///< close the thread (stops looping and waits for idle mode before joining the thread)

  // -- more fine control - but rarely used
  void threadOpen(bool waitForOpened=false);  ///< start the thread (in idle mode) (should be positive for changes)
  void threadStep();                    ///< trigger (multiple) step (idle -> working mode) (wait until idle? otherwise calling during non-idle -> error)
  void threadStop(bool wait=false);     ///< stop looping
  void threadCancel();                  ///< a hard kill (pthread_cancel) of the thread

  void waitForOpened() { status.waitForNotEq(tsIsClosed); status.waitForNotEq(tsToOpen); }
  void waitForIdle() { status.waitForEq(tsIDLE); }
  bool isIdle() { return status.get()==tsIDLE; }
  bool isClosed() { return !thread; }

  void listenTo(Var_base& v);
  void stopListening();
  void stopListenTo(Var_base& c);
  void listeningCallback(Var_base* v);

  /** use this to open drivers/devices/files and initialize
   *  parameters; this is called within the thread */
  virtual void open() {}

  /** The most important method of all of this: step does the actual
   *  computation of the thread. Access
   *  the variables by calling the x.get(), x.set() or
   *  x.[read|write|de]Access(), where VAR(TYPE, x) was
   *  declared. */
  virtual void step() { LOG(-1) <<"you're calling the 'pseudo-pure virtual' step(), which should be overloaded (are you in a destructor?)"; }

  /** use this to close drivers/devices/files; this is called within
   *  the thread */
  virtual void close() {}

private:
  void main(); //this is the thread main
};

} //namespace
