QUIT
WAIT
INFEASIBLE
ANY
Terminate

FOL_World{
  hasWait=false
  gamma = 1.
  stepCost = 1.
  timeCost = 0.
}

## basic predicates
gripper
obj
table

on
busy     # involved in an ongoing (durative) activity
held     # object is held by an gripper

## KOMO symbols
above

touch
impulse
stable
stableOn
dynamic
dynamicOn
liftDownUp

## objects
table1, table2, table3, obj0, obj1, obj2, obj3, tray, pr2r, pr2l,

## initial state (generated by the code)
START_STATE { (table table2) (obj obj0) (obj obj1) (obj obj2) (obj obj3) (table tray) (gripper pr2r) (gripper pr2l) (on table1 obj0) (on table1 obj1) (on table1 obj2) (on table1 obj3) }

### RULES

#####################################################################

Rule termination{
  { (on tray obj0) }
  { (QUIT) }
}

### Reward
REWARD {
}

#####################################################################

DecisionRule pick {
  A, X, Y
  { (on A Y) (gripper X) (obj Y) (busy X)! (held Y)! (INFEASIBLE pick X Y)! }
  { (stableOn A Y)! (above Y A)! (on A Y)!
    (busy X) (held Y) (touch X Y) (stable X Y) (on X Y)
    }
}

#####################################################################

DecisionRule place {
  X, Y, Z,
  { (gripper X) (held Y) (on X Y) (table Z) }
  { (busy X)! (held Y)! (touch X Y)! (stable X Y)! (on X Y)!
    (on Z Y) (above Y Z) (stableOn Z Y) tmp(touch X Y)
    (INFEASIBLE pick ANY Y)! block(INFEASIBLE pick ANY Y) }
}

#####################################################################

