name: CMake

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        source _make/install.sh vars_only #defines the following dependency packages
        sudo apt install --yes ${ubuntu_rai}
        _make/install.sh libccd
        _make/install.sh fcl
        _make/install.sh libann
    - name: cmake configure
      run: cmake . -B build -DBUILD_TESTS=ON -DUSE_PHYSX=OFF
    - name: build
      run: make -C build
